version: "3.9"
services:
  api:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    tty: true
    tty: true
    working_dir: /app
    command: ./gradlew bootrun

  db:
    image: postgres:15.4-bullseye
    environment:
      - POSTGRES_PASSWORD=aokim
      - POSTGRES_USER=root
    volumes:
      - postgres_volume:/var/lib/postgresql
    ports:
      - 3300:5432

volumes:
  postgres_volume:
